### ISSUE TITLE
ユーザーが同じものを複数個買い物をしたときにフォームで個数を入力できない

### ISSUE THREAD

**Issue by miwasasaki** [mym-kingbob/CommonFeePlan#1]
### これを解決することで
- ユーザーの入力の手間を省くことができる
- データログ的にも細かな情報が取れるので、精度の高い分析ができる

### 方針
- フォームを改善する
- 値段と個数をかく欄を作る

**Comment by komayama** [comment]
フォームを直しましょう

**Comment by miwasasaki** [comment]
今まで使ってたフォームをコピーして直してみた

 (仮)買いものをした I bought
https://docs.google.com/forms/d/194auLoJe-ja6kme62XrTF9b3Oakn74mOYA_pFZgOdng/edit

**変更点**
- 電卓のURLを値段の綱目の説明欄に追加
- 何個買ったかかく場所を追加

**迷っている点**
- ユーザーが他の種類のものを買ったとき、同じフォームでまた入力させるのがいいか(今は設定してない)、もう一度フォームに書いてもらうUXにするか(今設定してる)
データの保持の関係とかで別にした方が良い？と思ったけど意見聞きたいです

**Comment by miwasasaki** [comment]
@mym-kingbob

**Comment by komayama** [comment]
@miwasasaki 
> ユーザーが他の種類のものを買ったとき、同じフォームでまた入力させるのがいいか(今は設定してない)、もう一度フォームに書いてもらうUXにするか(今設定してる)
データの保持の関係とかで別にした方が良い？と思ったけど意見聞きたいです

最初はよく買うものをリストを保存しておき，補完機能で表示するほうがユーザが入力する手間が省けそう．
あと，電卓機能は外部URLを呼び出すより自分たちのページで完結するほうがページをいったりきたりしなくていいのでストレスは減る可能性がある
ここまで機能を実装するとGoogleフォームでは限界がありそう

**Comment by miwasasaki** [comment]
休みの日にごめんなさい笑

>最初はよく買うものをリストを保存しておき

そうだよね、1ヶ月やったからすぐ作れそうだし、作ってみるリスト

>電卓機能は外部URLを呼び出すより自分たちのページで完結するほうがページをいったりきたりしなくていいのでストレスは減る可能性がある
ここまで機能を実装するとGoogleフォームでは限界がありそう

Agree

**Comment by miwasasaki** [comment]
それかもうスプレッドシート上で計算するとか？

**Comment by komayama** [comment]
スプレッドシート上で計算するのは良さそうだね
そうすると，どうやってユーザに見せるかがポイントになるなぁ

**Comment by komayama** [comment]
@ryoju-ohata 
Google Form は使用しないので、こちらの対応もよろしくお願いいたします。

**Comment by komayama** [comment]
https://github.com/komayama/CommonFeePlan/issues/6 へ issue をまとめたので一旦クローズとします。
