### ISSUE TITLE
【購入画面（purchase）】Item Price を数字のみ入力制限する

### ISSUE THREAD

**Issue by komayama** [mym-kingbob/CommonFeePlan#11]
商品の料金を入力する Item Price では、現状はキーボードとなっており、数字以外の文字列を入力することができる。
数字のみ入力できるように制限することで、ユーザからの入力間違いは減る。

**Comment by ryoju-ohata** [comment]
@komayama 
スマホでの検証のため、masterブランチで対応済み

**Comment by komayama** [comment]
対応済み
