### ISSUE TITLE
払ったのにアテンションが飛んでしまう

### ISSUE THREAD

**Issue by miwasasaki** [mym-kingbob/CommonFeePlan#3]

**Comment by komayama** [comment]
@ryoju-ohata 
フロントエンド改修のため、Google Form は使用しないです。独自のフロントエンドを構築し API を呼び出す仕様へ変更します。

FYI: @miwasasaki

**Comment by komayama** [comment]
https://github.com/komayama/CommonFeePlan/issues/6 へまとめたので一旦クローズとします。
